name = "lenscrafter"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "../../dist"
binding = "ASSETS"

# Bindings
[ai]
binding = "AI"

[browser]
binding = "BROWSER"

[[kv_namespaces]]
binding = "LENS_CACHE"
id = "da843a8df99d48c58de3f65fa0ed6091"
preview_id = "da843a8df99d48c58de3f65fa0ed6091"

[observability]
enabled = true

[vars]
AI_PRIMARY_BASE_URL = "https://ai-primary-worker.ai-rail-account.workers.dev"
AI_PRIMARY_FALLBACK_TO_LOCAL = "false"
